#+TITLE: CS 161 Day 2
#+DATE: 4/4/2018
#+OPTIONS: toc:nil

* What's a computer?
** Calculator?
   It performs computations... It is a kind of an example of a
   computer however the calculator is not general purpose programmable
   device.

** Smart phone?
* Important characteristics
** Take inputs
** Perform operations
** Generate Outputs

* History of computers
** Abbacus
   Mechanical aid to computation
** Pascal, Leibnitz, and others had similar devices
** Charles Babbage

   Idea of a programmable, general purpose computer. Had designs
   however he never completed one. He had a history of getting
   distracted by better ideas.

   First idea was the "difference engine". Sponsored by gov't. Purpose
   was to generate sheets of logarithmic tables for
   computations. These were generated by people by hand.

   "Analytical engine" -- the device that would have been
   programmable. Not limited to arithmetic.

**  Ada Lovelace - actually programmed some of these devices.
    Father was a famous poet... Ada's mother had her trained in
    mathematics because she didn't want her daughter to be overly
    influence by "poetic passion"


** Alan Turing
   An actual programmable computer did not come around until
   WWII. There was an effort to decode German "Enigma" code. This was
   not an actual computer. The general purpose computer called the
   "Collosus" device.

** Germany
   Not as fast as fully electronic computer... Used electrical relays

** US (ADC Computer)
   First fully electronic computer (perhaps) but not first general
   purpose computer.

   First actual computer (Eniac???) was used for calculating
   ballistics and trajectories

* What is hardware and what is software?

** Software
   Operating System: manage resources of computer and running
   application software.

** Hardware
   Central Processing Unit (CPU): Carries out the calculations

** Memory
   Random Access Memory (RAM): Volatile -- you lose it when you turn
   off the machine however it is MUCH faster.

   Secondary Storage (Hard Drive, Disk Drive, etc...): Long term
   storage


* Actual programming stuff
  We will be using the high-level language C++. In C++ we write source
  code files that are then translated into executable machine language
  by a compiler (g++).

  Code does not need to be strictly linear (think loops and
  conditional expressions) however the language must be precise -- NO
  ambiguity.
